<?php

/**
 * BaseMpGdp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $dari_description
 * @property string $hs_code
 * @property integer $level
 * @property integer $parent_id
 * @property integer $status_id
 * @property MpStatus $MpStatus
 * @property MpGdp $MpGdp
 * @property Doctrine_Collection $Gdps
 * @property Doctrine_Collection $GdpRecords
 * 
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getDescription()      Returns the current record's "description" value
 * @method string              getDariDescription()  Returns the current record's "dari_description" value
 * @method string              getHsCode()           Returns the current record's "hs_code" value
 * @method integer             getLevel()            Returns the current record's "level" value
 * @method integer             getParentId()         Returns the current record's "parent_id" value
 * @method integer             getStatusId()         Returns the current record's "status_id" value
 * @method MpStatus            getMpStatus()         Returns the current record's "MpStatus" value
 * @method MpGdp               getMpGdp()            Returns the current record's "MpGdp" value
 * @method Doctrine_Collection getGdps()             Returns the current record's "Gdps" collection
 * @method Doctrine_Collection getGdpRecords()       Returns the current record's "GdpRecords" collection
 * @method MpGdp               setName()             Sets the current record's "name" value
 * @method MpGdp               setDescription()      Sets the current record's "description" value
 * @method MpGdp               setDariDescription()  Sets the current record's "dari_description" value
 * @method MpGdp               setHsCode()           Sets the current record's "hs_code" value
 * @method MpGdp               setLevel()            Sets the current record's "level" value
 * @method MpGdp               setParentId()         Sets the current record's "parent_id" value
 * @method MpGdp               setStatusId()         Sets the current record's "status_id" value
 * @method MpGdp               setMpStatus()         Sets the current record's "MpStatus" value
 * @method MpGdp               setMpGdp()            Sets the current record's "MpGdp" value
 * @method MpGdp               setGdps()             Sets the current record's "Gdps" collection
 * @method MpGdp               setGdpRecords()       Sets the current record's "GdpRecords" collection
 * 
 * @package    MP
 * @subpackage model
 * @author     abas rafiq
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMpGdp extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mp_gdp');
        $this->hasColumn('name', 'string', 225, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 225,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('dari_description', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('hs_code', 'string', 8, array(
             'type' => 'string',
             'unique' => true,
             'length' => 8,
             ));
        $this->hasColumn('level', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('status_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MpStatus', array(
             'local' => 'status_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('MpGdp', array(
             'local' => 'parent_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('MpGdp as Gdps', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $this->hasMany('MpGdpRecord as GdpRecords', array(
             'local' => 'id',
             'foreign' => 'gdp_id'));
    }
}