<?php

/**
 * BaseMpUserComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $comment
 * @property integer $user_id
 * @property timestamp $creation_date
 * @property MpUser $MpUser
 * 
 * @method string        getName()          Returns the current record's "name" value
 * @method string        getComment()       Returns the current record's "comment" value
 * @method integer       getUserId()        Returns the current record's "user_id" value
 * @method timestamp     getCreationDate()  Returns the current record's "creation_date" value
 * @method MpUser        getMpUser()        Returns the current record's "MpUser" value
 * @method MpUserComment setName()          Sets the current record's "name" value
 * @method MpUserComment setComment()       Sets the current record's "comment" value
 * @method MpUserComment setUserId()        Sets the current record's "user_id" value
 * @method MpUserComment setCreationDate()  Sets the current record's "creation_date" value
 * @method MpUserComment setMpUser()        Sets the current record's "MpUser" value
 * 
 * @package    MP
 * @subpackage model
 * @author     abas rafiq
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMpUserComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mp_user_comment');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('comment', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('creation_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MpUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}