<?php

/**
 * BaseMpCountry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $abbreviation
 * @property string $code
 * @property integer $status_id
 * @property MpStatus $MpStatus
 * 
 * @method string    getName()         Returns the current record's "name" value
 * @method string    getDescription()  Returns the current record's "description" value
 * @method string    getAbbreviation() Returns the current record's "abbreviation" value
 * @method string    getCode()         Returns the current record's "code" value
 * @method integer   getStatusId()     Returns the current record's "status_id" value
 * @method MpStatus  getMpStatus()     Returns the current record's "MpStatus" value
 * @method MpCountry setName()         Sets the current record's "name" value
 * @method MpCountry setDescription()  Sets the current record's "description" value
 * @method MpCountry setAbbreviation() Sets the current record's "abbreviation" value
 * @method MpCountry setCode()         Sets the current record's "code" value
 * @method MpCountry setStatusId()     Sets the current record's "status_id" value
 * @method MpCountry setMpStatus()     Sets the current record's "MpStatus" value
 * 
 * @package    MP
 * @subpackage model
 * @author     abas rafiq
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMpCountry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mp_country');
        $this->hasColumn('name', 'string', 225, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 225,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('abbreviation', 'string', 2, array(
             'type' => 'string',
             'unique' => true,
             'length' => 2,
             ));
        $this->hasColumn('code', 'string', 3, array(
             'type' => 'string',
             'unique' => true,
             'length' => 3,
             ));
        $this->hasColumn('status_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MpStatus', array(
             'local' => 'status_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}