<?php

/**
 * BaseMpPeriod
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property integer $status_id
 * @property MpStatus $MpStatus
 * @property Doctrine_Collection $BulkUploads
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method integer             getStatusId()    Returns the current record's "status_id" value
 * @method MpStatus            getMpStatus()    Returns the current record's "MpStatus" value
 * @method Doctrine_Collection getBulkUploads() Returns the current record's "BulkUploads" collection
 * @method MpPeriod            setName()        Sets the current record's "name" value
 * @method MpPeriod            setDescription() Sets the current record's "description" value
 * @method MpPeriod            setStatusId()    Sets the current record's "status_id" value
 * @method MpPeriod            setMpStatus()    Sets the current record's "MpStatus" value
 * @method MpPeriod            setBulkUploads() Sets the current record's "BulkUploads" collection
 * 
 * @package    MP
 * @subpackage model
 * @author     abas rafiq
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMpPeriod extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mp_period');
        $this->hasColumn('name', 'string', 225, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 225,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('status_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MpStatus', array(
             'local' => 'status_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('MpBulkUploadRecord as BulkUploads', array(
             'local' => 'id',
             'foreign' => 'period_id'));
    }
}