<?php

/**
 * BaseMpDocumentType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property boolean $is_public
 * @property integer $status_id
 * @property MpStatus $MpStatus
 * @property Doctrine_Collection $Documents
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method boolean             getIsPublic()    Returns the current record's "is_public" value
 * @method integer             getStatusId()    Returns the current record's "status_id" value
 * @method MpStatus            getMpStatus()    Returns the current record's "MpStatus" value
 * @method Doctrine_Collection getDocuments()   Returns the current record's "Documents" collection
 * @method MpDocumentType      setName()        Sets the current record's "name" value
 * @method MpDocumentType      setDescription() Sets the current record's "description" value
 * @method MpDocumentType      setIsPublic()    Sets the current record's "is_public" value
 * @method MpDocumentType      setStatusId()    Sets the current record's "status_id" value
 * @method MpDocumentType      setMpStatus()    Sets the current record's "MpStatus" value
 * @method MpDocumentType      setDocuments()   Sets the current record's "Documents" collection
 * 
 * @package    MP
 * @subpackage model
 * @author     abas rafiq
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMpDocumentType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mp_document_type');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('status_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MpStatus', array(
             'local' => 'status_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('MpDocument as Documents', array(
             'local' => 'id',
             'foreign' => 'document_type_id'));
    }
}