<?php

/**
 * BaseMpSystemParameter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $key1
 * @property string $value1
 * 
 * @method string            getKey1()   Returns the current record's "key1" value
 * @method string            getValue1() Returns the current record's "value1" value
 * @method MpSystemParameter setKey1()   Sets the current record's "key1" value
 * @method MpSystemParameter setValue1() Sets the current record's "value1" value
 * 
 * @package    MP
 * @subpackage model
 * @author     abas rafiq
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMpSystemParameter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mp_system_parameter');
        $this->hasColumn('key1', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('value1', 'string', 225, array(
             'type' => 'string',
             'length' => 225,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}