<?php

/**
 * BaseMpDepartment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $parent_organization
 * @property string $location
 * @property integer $status_id
 * @property MpStatus $MpStatus
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $DocumentRecords
 * 
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method string              getParentOrganization()  Returns the current record's "parent_organization" value
 * @method string              getLocation()            Returns the current record's "location" value
 * @method integer             getStatusId()            Returns the current record's "status_id" value
 * @method MpStatus            getMpStatus()            Returns the current record's "MpStatus" value
 * @method Doctrine_Collection getUsers()               Returns the current record's "Users" collection
 * @method Doctrine_Collection getDocumentRecords()     Returns the current record's "DocumentRecords" collection
 * @method MpDepartment        setName()                Sets the current record's "name" value
 * @method MpDepartment        setDescription()         Sets the current record's "description" value
 * @method MpDepartment        setParentOrganization()  Sets the current record's "parent_organization" value
 * @method MpDepartment        setLocation()            Sets the current record's "location" value
 * @method MpDepartment        setStatusId()            Sets the current record's "status_id" value
 * @method MpDepartment        setMpStatus()            Sets the current record's "MpStatus" value
 * @method MpDepartment        setUsers()               Sets the current record's "Users" collection
 * @method MpDepartment        setDocumentRecords()     Sets the current record's "DocumentRecords" collection
 * 
 * @package    MP
 * @subpackage model
 * @author     abas rafiq
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMpDepartment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mp_department');
        $this->hasColumn('name', 'string', 225, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 225,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('parent_organization', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('location', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('status_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MpStatus', array(
             'local' => 'status_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('MpUser as Users', array(
             'local' => 'id',
             'foreign' => 'department_id'));

        $this->hasMany('MpDocumentRecord as DocumentRecords', array(
             'local' => 'id',
             'foreign' => 'department_id'));
    }
}