<?php

/**
 * MpAccessLevelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MpAccessLevelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MpAccessLevelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MpAccessLevel');
    }
}