<?php

/**
 * MpBulkUploadRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MpBulkUploadRecordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MpBulkUploadRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MpBulkUploadRecord');
    }
}