<?php

/**
 * MpCountryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MpCountryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MpCountryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MpCountry');
    }
}