<?php

/**
 * MpDepartmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MpDepartmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MpDepartmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MpDepartment');
    }
}