<?php

/**
 * MpDocumentRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MpDocumentRecordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MpDocumentRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MpDocumentRecord');
    }
}