<?php

/**
 * MpDocumentTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MpDocumentTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MpDocumentTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MpDocumentType');
    }
}