<?php

/**
 * MpGdpRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MpGdpRecordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MpGdpRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MpGdpRecord');
    }
}