<?php

/**
 * MpGdpTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MpGdpTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MpGdpTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MpGdp');
    }
}