<?php

/**
 * MpPeriodTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MpPeriodTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MpPeriodTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MpPeriod');
    }
}