<?php

/**
 * MpSessionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MpSessionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MpSessionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MpSession');
    }
}