<?php

/**
 * MpStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MpStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MpStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MpStatus');
    }
}