<?php

/**
 * MpSystemParameterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MpSystemParameterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MpSystemParameterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MpSystemParameter');
    }
}