<?php

/**
 * MpTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MpTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MpTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MpType');
    }
}