<?php

/**
 * MpUnitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MpUnitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MpUnitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MpUnit');
    }
}