<?php

/**
 * MpUserCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MpUserCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MpUserCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MpUserComment');
    }
}